language: node_js

node_js:
  - "stable"
 
install:
  - npm install

services:
  - postgresql
  
before_script:
  - psql -c 'create database Teamwork;' -U postgres
  
cache:
  directories:
    - "node_modules"
