sudo: false


language: node_js

node_js:
  - "stable"
 
install:
  - npm install

services:
  - postgresql
  
before_script:
  - psql -c 'create database Teamwork;' -U postgres
  - psql -c postgres --password="Boywonder47" < backend/queries.sql
  

cache:
  directories:
    - "backend/node_modules"
