sudo: false

before_install: cd backend

language: node_js

node_js:
  - "stable"
 
install:
  - npm ci

services:
  - postgresql
  
before_script:
  - psql -c 'create database Teamwork;' -U postgres
  - psql -c ./backend/queries.sql
  

cache:
  directories:
    - "backend/node_modules"
