language: node_js

node_js:
  - "stable"
 
install:
  - npm install

services:
  - postgresql
  
before_script:
  - psql -c 'create database Teamwork;' -U postgres
  
script:
  - backend/queries.sql 
  

cache:
  directories:
    - "backend/node_modules"
