CREATE TABLE Admin (
  ID SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);


CREATE TABLE Employee (
  ID SERIAL PRIMARY KEY,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  gender VARCHAR(255) NOT NULL,
  jobRole VARCHAR(255) NOT NULL,
  department VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL
);


CREATE TABLE Article (
  ID SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  article VARCHAR(255) NOT NULL,
  createdOn DATE NOT NULL DEFAULT CURRENT_DATE,
  employee_id INT REFERENCES Employee(ID) NOT NULL

);
